# Generated by Django 5.0 on 2023-12-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartitem_unit_price_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('PR', 'Preparing'), ('OW', 'On The Way'), ('C', 'Completed'), ('CA', 'Cancelled')], default='P', max_length=2),
        ),
    ]
