# Generated by Django 5.0 on 2024-01-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_student_image_courseaim_coursecontents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='NO', upload_to='store/courses/images'),
        ),
        migrations.DeleteModel(
            name='CourseImage',
        ),
    ]
