# Generated by Django 5.0 on 2024-01-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_coursetutorials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetutorials',
            old_name='pdf',
            new_name='video',
        ),
        migrations.CreateModel(
            name='CourseDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='store/course/videos')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.course')),
            ],
        ),
    ]
