# Generated by Django 5.0 on 2024-01-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_coursedocuments_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
