# Generated by Django 5.0 on 2024-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('CA', 'Cancelled')], default='P', max_length=2),
        ),
    ]
